### ISSUE TITLE
In nested dictionaries, how do you compare dictionaries for a single key?

### ISSUE THREAD

**Issue by Djones4822** [rmotr/pyp-questions#2]
I have a set of data that I've collected into a nested dictionary. This dictionary is for schools and the way they assign a grade to a GPA point scale (0-4) and their associated number ranges and letters for that grade. Ithas 2 levels to it, with the final level yielding a year-range, and a big list.

here is the format:
 `my_dict = { id1: { yearrange1: [(Point1, [Letter1, Range1]), (Point2, [Letter2, Range2]), ... , (PointN, [LetterN, RangeN])]`

Here is an example:

```python
my_dict["113040"] = 
        "2002"-"2008": [('"0"', ['"F"', '"69"-"0"']), ('"1"', ['"D"', '"76"-"70"']), ('"2"', ['"C"', '"84"-"77"']), ('"3"', ['"B"', '"92"-"85"']), ('"4"', ['"A"', '"100"-"93"'])]
       "2009"-"2025":  [('"0"', ['"F"', '"69"-"0"']), ('"1"', ['"D"', '"73"-"70"']), ('"2"', ['"C"', '"79"-"74"']), ('"3"', ['"B"', '"89"-"80"']), ('"4"', ['"A"', '"110"-"90"'])]
```

What I want to do is see if the grading schemes between years are the same. So for each key, are all the values the same. My problem is that a dictionary isn't hashable, and the nested nature of it is throwing me off.

Can anyone help me figure out a solution? I have [found this](http://stackoverflow.com/a/17821124/2449301) but I'm not sure if this is the right implementation (the second part). 

Thanks everyone!

**Comment by santiagobasulto** [comment]
David, I'm not sure if I understand what you're trying to do, but I think it shouldn't be hard.

Can you provide examples of what you're getting (I assume `dict["113040"]`) and what you need as an output?

For example, this is what I understand. You have this data:

```python
{
    "113040": {
        "2002-2008": [
            ('"0"', ['"F"', '"69"-"0"']),
            ('"1"', ['"D"', '"76"-"70"']),
            ('"2"', ['"C"', '"84"-"77"']),
            ('"3"', ['"B"', '"92"-"85"']),
            ('"4"', ['"A"', '"100"-"93"'])
        ],
       "2009-2025": [
           ('"0"', ['"F"', '"69"-"0"']),
           ('"1"', ['"D"', '"73"-"70"']),
           ('"2"', ['"C"', '"79"-"74"']),
           ('"3"', ['"B"', '"89"-"80"']),
           ('"4"', ['"A"', '"110"-"90"'])
       ]
    }
}
```

And you're trying to know if in 2002-2008, the grading system for an **A** was the same as for 2009-2025, which of course is not true because an **A** in 2002-2008 was "100"-"93" and in 2009-2025 it's "110"-"90".

Assuming that what I understood is ok, I'd build a script to transform the original dict into something like:

```python
{
    "113040": {
        "A": {
            "2002-2008": '"100"-"93"',
            "2009-2025": '"110"-"90"',
        }
    }
}
```

**Comment by tychovk** [comment]
Without transforming the original dict, you could do this. It's important that the values are written in the same order (all from "F" to "A") because you're comparing lists.

Extended example dictionary:

    my_dict = \
    {
        "113040": {
            "2002-2008": [
                ('"0"', ['"F"', '"69"-"0"']),
                ('"1"', ['"D"', '"76"-"70"']),
                ('"2"', ['"C"', '"84"-"77"']),
                ('"3"', ['"B"', '"92"-"85"']),
                ('"4"', ['"A"', '"100"-"93"'])
            ],
           "2009-2025": [
               ('"0"', ['"F"', '"69"-"0"']),
               ('"1"', ['"D"', '"73"-"70"']),
               ('"2"', ['"C"', '"79"-"74"']),
               ('"3"', ['"B"', '"89"-"80"']),
               ('"4"', ['"A"', '"110"-"90"'])
           ],
          "2026-2050": [
               ('"0"', ['"F"', '"69"-"0"']),
               ('"1"', ['"D"', '"73"-"70"']),
               ('"2"', ['"C"', '"79"-"74"']),
               ('"3"', ['"B"', '"89"-"80"']),
               ('"4"', ['"A"', '"110"-"90"'])
           ],
           "2051-2075": [
               ('"0"', ['"F"', '"69"-"0"']),
               ('"1"', ['"D"', '"73"-"70"']),
               ('"2"', ['"C"', '"79"-"74"']),
               ('"3"', ['"B"', '"89"-"80"']),
               ('"4"', ['"A"', '"110"-"90"'])
           ],
           "2076-3000": [
               ('"0"', ['"F"', '"69"-"0"']),
               ('"1"', ['"D"', '"73"-"70"']),
               ('"2"', ['"C"', '"79"-"74"']),
               ('"3"', ['"B"', '"89"-"80"']),
               ('"4"', ['"A"', '"110"-"90"'])
           ]
        }
    }


This code gives you two lists with year-combinations, one for "same grading schemes", and one for "differing grading schemes":

    same_schemes = []
    differing_schemes = []
    for key in my_dict["113040"]:
        for other_key in my_dict["113040"]:
            key_comb = set((key, other_key))
            if key == other_key:
                continue
            elif my_dict["113040"][key] == my_dict["113040"][other_key]:
                if key_comb not in same_schemes:
                    same_schemes.append(key_comb)
            else:
                if key_comb not in differing_schemes:
                    differing_schemes.append(key_comb)


output:

    same_schemes: [{'2026-2050', '2009-2025'}, {'2026-2050', '2051-2075'}, {'2026-2050', '2076-3000'}, {'2009-2025', '2051-2075'}, {'2009-2025', '2076-3000'}, {'2051-2075', '2076-3000'}]

    differing_schemes: [{'2002-2008', '2026-2050'}, {'2002-2008', '2009-2025'}, {'2002-2008', '2051-2075'}, {'2002-2008', '2076-3000'}]

**Comment by santiagobasulto** [comment]
@Djones4822 I'm closing this one. Re-open it if you need further help.
