### ISSUE TITLE
Pymongo - update twice in same document (key)

### ISSUE THREAD

**Issue by tychovk** [rmotr/pyp-questions#3]
Hi guys,
I'm having trouble finding this out.

    db.accounts.update_one( { 
    'uname': uname, 'a' : { '$elemMatch' : { '$exists' : True }}}, 
    {'$set' : {'a' : a_values} },
    upsert = True
    )

    db.accounts.update_one( { 
    'uname': uname, 'b' : { '$exists' : True }}, 
    {'$set' : {'b' : b_values } },
    upsert = True
    )
When I execute this code, it inserts two different documents in the same collection, with the same uname (this is their first mention), I pretty much get two sets of documents, looking like this.. Variables a_values and b_values are dictionaries themselves:

    {'uname': uname, 'a': {a_values} }
    {'uname': uname, 'b': {b_values} }

How do I get it to do it so it looks like this:

    {'uname': uname, 'a': {a_values}, 'b': {b_values} }

Thank you in advance!

**Comment by tychovk** [comment]
*EDIT:* woohoo, figured it out. the first value really just has to be an indicator of the document, so I should just keep it at that. A fresh set of eyes (even if it were my own) really help, I guess.

        db.accounts.update_one( { 
        'uname': uname}, 
        {'$set' : {'a' : a_values} },
        upsert = True
        )
                

        db.accounts.update_one( { 
        'uname': uname}, 
        {'$set' : {'b' : b_values } },
        upsert = True
        )

**Comment by santiagobasulto** [comment]
:+1:
