### ISSUE TITLE
Table Printer - the most efficient way

### ISSUE THREAD

**Issue by tychovk** [rmotr/pyp-questions#4]
Hi everybody, after reading the class 2 material, I wanted to give this problem a shot:
For practice, write a program that does the following.
https://automatetheboringstuff.com/chapter6/ *Table Printer*
Write a function named printTable() that takes a list of lists of strings and displays it in a well-organized table with each column right-justified. Assume that all the inner lists will contain the same number of strings. For example, the value could look like this:

    tableData = [['apples', 'oranges', 'cherries', 'banana'],
             ['Alice', 'Bob', 'Carol', 'David'],
             ['dogs', 'cats', 'moose', 'goose']]

Your printTable() function would print the following:

      apples Alice  dogs
     oranges   Bob  cats
    cherries Carol moose
      banana David goose

Hint: Your code will first have to find the longest string in each of the inner lists so that the whole column can be wide enough to fit all the strings. You can store the maximum width of each column as a list of integers. The printTable() function can begin with colWidths = [0] * len(tableData), which will create a list containing the same number of 0 values as the number of inner lists in tableData. That way, colWidths[0] can store the width of the longest string in tableData[0], colWidths[1] can store the width of the longest string in tableData[1], and so on. You can then find the largest value in the colWidths list to find out what integer width to pass to the rjust() string method.

The following code works just fine:

    def table_printer(table):
        max_elems = [len(list1) for list1 in table]
        max_len_ele = [max([len(word) for word in list1]) for list1 in table]
        lines = ''
    
        for x in range(max(max_elems)):
            for index, col in enumerate(max_len_ele):
                lines = lines + table[index][x].rjust(col+3)
                if x + 1 > index:
                    continue
            print (lines)
            lines = ''

    

    tableData = [['apples', 'oranges', 'cherries', 'banana'],
             ['Alice', 'Bob', 'Carol', 'David'],
             ['dogs', 'cats', 'moose', 'goose']]
             
             
    print (table_printer(tableData))

Gives output:

         apples   Alice    dogs
        oranges     Bob    cats
       cherries   Carol   moose
         banana   David   goose
    None

*But I have two questions:*
Q1. What if one of the lists has more items than others, what would be the most efficient way to get a table anyway? e.g.:

    tableData = [['apples', 'oranges', 'cherries', 'banana'],
             ['Alice', 'Bob', 'Carol', 'David'],
             ['dogs', 'cats', 'moose', 'goose', 'duckduckgo']]

Wanted output:

         apples   Alice         dogs
        oranges     Bob         cats
       cherries   Carol        moose
         banana   David        goose
                          duckduckgo

Q2. And how to get rid of the "None" at the end?

**Comment by santiagobasulto** [comment]
Interesting problem Tycho! (I'm going to stole it for the class)

To get rid of the None, just don't "print" your function invocation. You're doing:
`print(table_printer(tableData))` which is the equivalent of:

```python
result = table_printer(tableData)
print(result)
```
Your `table_printer` function doesn't return anything, it just prints stuff in screen. If you remember what we said about functions, functions in python without any explicit `return` will return None by default. So `result` in that case is None. So basically you're doing `print(result) == print(None)` :)

**Comment by tychovk** [comment]
Good point! How would you go about it (efficiently) when one list in the list has more elements than the others?

**Comment by martinzugnoni** [comment]
Hi Tycho, pretty interesting question.

In my opinion, there're two things that are affecting the efficiency of this script while printing the table.
- One is that you are iterating through all the elements in the table so many times. In your code sample I see your are doing it at least 3 times. This wouldn't be a problem if it's a small table, but picture a table with millions of rows/columns.
- Second is the way you have "designed" your data structure. Each sub-list in the table in your sample represents a column, but while printing the table you need to iterate by row. That make things a little bit more complicated.

What I propose is:
1) Design the table data structure the other way around:
```python
table_data = [  # do not use camel case in python variable names, it's not pythonic ;-)
    ['apples', 'Alice', 'dogs'],
    ['oranges', 'Bob', 'cats'],
    ['cherries', 'Carol', 'moose'],
    ['banana', 'David', 'goose'],
    ['', '', 'duckduckgo'],
]
```

Using this data structure, you can resolve the problem in a few lines, using no indexes or counters
```python
# find longest string in the whole table
max_length = max([max([len(e) for e in column]) for column in table_data])

# print the whole table right-aligned
for row in table_data:
    print(''.join([e.rjust(max_length) for e in row]))
```

Hope it helps :)

**Comment by tychovk** [comment]
This is great, this helps out a ton! So if the table was fed to me by something else, rewriting the table would be a good start then.

By the way, this is all from one of your readings (https://automatetheboringstuff.com/chapter6/ see the bottom practice), so maybe you want to revisit something there... ;-). I'm not too happy about camel case either.
