### ISSUE TITLE
Timing code - how to determine the run time of a function?

### ISSUE THREAD

**Issue by jaime-h** [rmotr/pyp-questions#5]
Basically had a conversation around which algorithm/function runs faster. How do we determine that?

**Comment by tychovk** [comment]
Try this out:

    #put this on the top of your script
    from datetime import *
    startTime = datetime.now()

    #put this below the part so the above and this encompasses what you want too measure the time of
    print ('This took about', datetime.now().microsecond - startTime.microsecond, 'microseconds')

**Comment by jivanyatra** [comment]
You could turn this into a decorator and reuse it as you see fit.

**Comment by santiagobasulto** [comment]
The correct way to do it is using the [timeit](https://docs.python.org/2/library/timeit.html) module. See an example here: http://stackoverflow.com/a/8220943/198212

**Comment by tychovk** [comment]
This was pretty difficult to find, so here goes sharing:

    def a_function(an_argument):
        return an_argument**an_argument**an_argument #for example



    import timeit
    average_out_of = 10
    the_argument = 50000
    result = timeit.Timer('a_function({})'.format(the_argument), 'from __main__ import a_function').timeit(average_out_of)

    print ("Out of ", result)
