### ISSUE TITLE
Cherrypicking elements to count in a list

### ISSUE THREAD

**Issue by tychovk** [rmotr/pyp-questions#6]
Hi all,

I was just thinking: what if you want to check specific indices in a list for characteristics, how would you go about it?

Say we have this list:

    a_list = [1, 4, 3, 4, 'a', 'c', '5', 2, 4] 

And I want to count the amount of occurrences of 4 in indices 3, 4, and 8. 
The result should be 2.

Obviously counting in the whole list one would do this way:

    a_list.count(4)

One way I can think of is:

    [a_list[3], a_list[4], a_list[8]].count(4)

Or if we have a list of the indices:

    check_indices = [3,4,8]

    [a_list[x] for x in check_indices].count(4)

**Comment by santiagobasulto** [comment]
You could use slicing if the indexes are consecutive:

```
a_list = [1, 4, 3, 4, 'a', 'c', '5', 2, 4]
a_list[3:8].count(4)
```

**Comment by tychovk** [comment]
Thanks for the reply!

However when I try this on `list_c = [1,2,3,4]` it gives this error (Python 3):

      File "~\test.py", line 156, in <module>
    print (list(filter(filter_condition, list_c)))
  File "~\test.py", line 154, in filter_condition
    idx, elem = idx_elem
TypeError: 'int' object is not iterable



    def filter_condition(idx_elem):
        idx, elem = idx_elem
        return elem == 4 and idx in check_indices
    print (list(filter(filter_condition, list_c)))

**Comment by santiagobasulto** [comment]
Forgot the `enumerate`! Updated.

**Comment by tychovk** [comment]
list_c = [1,2,3,4,4,5,6,7,4,9,10]

    def filter_condition(idx_elem):
        check_indices = [3,4,8]
        idx, elem = idx_elem
        return elem == 4 and idx in check_indices

    index_and_element = list( filter(filter_condition, enumerate(list_c)) )
    # output: [(3, 4), (4, 4), (8, 4)]

    print (len(index_and_element))
    # output: 3

**Comment by vihu** [comment]
I'd do this:

```python
a = [1, 4, 3, 4, 'a', 'c', '5', 2, 4] 
print [(idx, num) for idx, num in enumerate(a) if num == 4] #returns [(3, 4), (4, 4), (8, 4)]

**Comment by santiagobasulto** [comment]
Ok, sorry, I don't know how I forgot to mention this. A `filter` function can be included in a list comprehension, so basically it'd be:

```python
a_list = [1, 4, 3, 4, 'a', 'c', '5', 2, 4]
check_indices = [3,4,8]
[idx for idx, elem in enumerate(a_list) if (elem == 4 and idx in check_indices)]
```
@tychovk ^

**Comment by tychovk** [comment]
@vihu , your script however does not do what I'm looking for: it finds ANY position with 4. While what I want, is to look within specific indices, for "the number 4" (or whatever you're looking for)

**Comment by vihu** [comment]
@tychovk Santiago's addition fixes that :)
