### ISSUE TITLE
A way for a method to access class but also instance attributes

### ISSUE THREAD

**Issue by tychovk** [rmotr/pyp-questions#8]
For example: 

    class people:
           population = 0
        def __init__(self, name, subpop):
           self.name = name
           self.subpop = subpop
           people.population += subpop
    
       def death(self, cls):
           self.subpop -= 1
           cls.population -= 1

In this case below, I'm wondering why you'd use "people.total_population instead of dutch.total_population, or mexican.total_population". I feel I'm being overly verbose here:

    class people:
       total_population = 0
       def __init__(self, name, population):
           self.name = name
           self.population = population
           people.total_population += population
    
       def death(self):
           self.population -= 1
           people.total_population -= 1

**Comment by santiagobasulto** [comment]
First things first. Classes should be [CamelCase](https://en.wikipedia.org/wiki/CamelCase). `class People`. More on [PEP8](https://www.python.org/dev/peps/pep-0008/).

There are two main ways to access a class method from an **_instance_method_** (*):

**Using self**

```python
class Widget(object):
    VALUE = 3

    def get_value(self):
        print(self.VALUE)
```

**Using the class**

```python
class Widget(object):
    VALUE = 3

    def get_value(self):
        print(Widget.VALUE)
```

The difference is that using `self` you hide the implementation detail to the method. If for any reason, VALUE changes from a class method to an instance method, you'll not need to change the method (in the first implementation). The problem resides in the assignment or modification of the class attribute. Try this example by yourself.

```python
class WorldPopulation(object):
    total_population = 0


class CountryPopulation(WorldPopulation):
    def __init__(self, country_name, initial_population=0):
        self.population = initial_population
        CountryPopulation.total_population += initial_population

    def death(self):
        self.population -= 1
        self.total_population -= 1

arg = CountryPopulation("Argentina", 40)
us = CountryPopulation("United States", 300)


def report_population():
    print("=======    Begining Report  ===========")
    print("WorldPopulation.total_population: {}".format(WorldPopulation.total_population))
    print("CountryPopulation.total_population: {}".format(CountryPopulation.total_population))
    print("arg.total_population: {}".format(arg.total_population))
    print("us.total_population: {}".format(us.total_population))
    print("=======      End Report      ===========\n")

report_population()

arg.death()
us.death()
report_population()
```python

Try using the class name (CountryPopulation), try using the parent name (WorldPopulation) or self. You'll see different results.

**Comment by tychovk** [comment]
I hadn't replied yet, but thank you for the example, it's really insightful!
